spring.application.name=test-spring

server.port=8080
server.error.include-exception=true
server.error.include-stacktrace=always
server.tomcat.threads.max=200
server.connection-timeout=5s
server.max-http-header-size=8KB
server.tomcat.max-swallow-size=2MB

# Database connection settings
spring.datasource.url=jdbc:postgresql://my_app_db:5432/local_mcd_test
spring.datasource.username=mc_duck
spring.datasource.password=mc_duck

# Optional: Specify the driver class name explicitly (often not necessary in Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate settings (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true